### PR TITLE
add the extractor script for PJSIP

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
@fredericlepied I noticed that I miss configured the branch protection. It is now fixed but I cannot get Zuul to check this PR. Help!

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
I'm not sure to like the test
I mean it only test that script does not fail and send json as output, we don't really tests the **values**
I agree that converting the real doc is the best real test, but with this structure it's hard to say if the synopsis is really extracted into the synopsis field

I would like to have a more succinct test will all possible values
Also if you want to keep the whole PJSIP test, then you can remove the output, because IMO in this test, we don't care of the output, we just want no error from the command. If you validate the output with another output generated by the script, you cannot see if there are a mistake. You can only see there are difference between first version, but never validate the first version

**Comment by pc-m** [comment]
> I'm not sure to like the test
> I mean it only test that script does not fail and send json as output, we don't really tests the **values**
> I agree that converting the real doc is the best real test, but with this structure it's hard to say if the synopsis is really extracted into the synopsis field
> 
> I would like to have a more succinct test will all possible values
> Also if you want to keep the whole PJSIP test, then you can remove the output, because IMO in this test, we don't care of the output, we just want no error from the command. If you validate the output with another output generated by the script, you cannot see if there are a mistake. You can only see there are difference between first version, but never validate the first version

I pushed a very slimmed down version of the xml and json. I only left a few sections that contained nested stuff that needs to be quoted. I really don't feel like building a mock xml file with all the nested stuff that I need to test for quoting.

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
